[package]
name = "rpos"
version = "0.1.0"
edition = "2021"

authors = ["kohbis <dev.kohbis@gmail.com>"]
categories = ["data-structures"]
description = "Cursor Manager on Table"
license = "MIT"
readme = "README.md"
repository = "https://github.com/kohbis/rpos"

[dependencies]
anyhow = "1.0.75"
